### ISSUE TITLE
Error Code

### ISSUE THREAD

**Issue by OG-Owen** [thPion/Screeps-Nooby-Guide#11]

**Comment by OG-Owen** [comment]
prototype.spawn:75
                else if (numberOfCreeps[role] < this.memory.minCreeps[role]) {
                                                                     ^
TypeError: Cannot read property 'harvester' of undefined
    at StructureSpawn.spawnCreepsIfNecessary (prototype.spawn:75:70)
    at Object.module.exports.loop (main:33:32)
    at __mainLoop:1:52
    at sigintHandlersWrap (vm.js:32:31)
    at sigintHandlersWrap (vm.js:73:12)

I have no idea what this means other than the harvester class cant be read. Thanks. Can it be updated/fixed

**Comment by Tim-Pohlmann** [comment]
I would assume you did not setup your memory correct. spawn.memory.minCreeps seems to be undefined.

**Comment by OG-Owen** [comment]
How would I go about doing that.

**Comment by Tim-Pohlmann** [comment]
I explained it in great detail in the corresponding video.
