### ISSUE TITLE
error code

### ISSUE THREAD

**Issue by xXtheguy52Xx** [thPion/Screeps-Nooby-Guide#6]
TypeError: Cannot read property 'harvester' of undefined
    at StructureSpawn.spawnCreepsIfNecessary (prototype.spawn:75:70)
    at Object.module.exports.loop (main:33:32)
    at __mainLoop:1:52

**Comment by xXtheguy52Xx** [comment]
ive noticed its labeling my spawn as a harvester but cant find how to stop it

**Comment by xXtheguy52Xx** [comment]
it should be noted i have now noticed that it makes sure to always have 1 harvester and nothing else

**Comment by Tim-Pohlmann** [comment]
I recommend checking out this comment thread:
https://www.youtube.com/watch?v=6b-ZZ6bROWI&lc=z12mzzmyyzmwtj2t423mytfyhqblxdoef

Tell me if that helped.

**Comment by xXtheguy52Xx** [comment]
It did thank you!
