### ISSUE TITLE
error with new spawn

### ISSUE THREAD

**Issue by jcomito** [thPion/Screeps-Nooby-Guide#9]
`TypeError: Cannot read property 'harvester' of undefined
    at StructureSpawn.spawnCreepsIfNecessary (prototype.spawn:75:70)
    at Object.module.exports.loop (main:33:32)
    at __mainLoop:1:52`

Starting a new spawn with your code. A harvester is spawned and begins collecting energy, but nothing else happens.

**Comment by DavydeVries** [comment]
I think you issue is the same as #6.

**Comment by Tim-Pohlmann** [comment]
duplicate of #6

**Comment by jcomito** [comment]
indeed, thanks. will give it a shot.
